### ISSUE TITLE
find_empty_memory_block is potentially broken

### ISSUE THREAD

**Issue by gdkchan** [reswitched/libtransistor#126]
So I noticed something really bad on this function.

- It uses a random 64-bits value to get a memory address that will be queried to test whenever the region is usable or not. This is bad, this not only makes the function nondeterministic but also makes it so that the time it will take to find a usable block totally is unpredictable aswell.
- The mask value used on the address is wrong. `0x0000007FFFFFF000` would be correct for a 39 bits, 4kb page aligned address space, but the address space on 2.0.0+ has 38 bits (according to switchbrew, at least...).
- Even through its afaik, not possible to run this on any fw other than 3.0.0, its good pratice to use svcGetInfo to get the correct address space size, and calculate the mask based on that.

This most likely makes hid_init fail with 0xdc01 (if the stars are not aligned for libtransistor to work and rand returned a value with bit 38 set).

**Comment by roblabla** [comment]
https://github.com/reswitched/libtransistor/issues/106

**Comment by misson20000** [comment]
I'm not concerned about the nondeterminism, since the address space is already randomized. I agree that you can't predict how long the function will take to find an empty block, but in my testing, it finds an empty block on the first try the *vast* majority of the time, and it shouldn't really matter how long it takes because in all but the most astronomically unlucky of scenarios, it is very fast, and it is intended called in a context of performing memory mappings during initialization, where it is not even expected to be fast.
